---
key_path: license_expires_at
description: The date the license ends
product_section: fulfillment
product_stage: fulfillment
product_group: group::license
product_category: collection
value_type: object
status: data_available
time_frame: none
data_source: license
distribution:
- ee
tier:
- premium
- ultimate
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/557
