---
name: secure_security_and_compliance_configuration_page_on_ce
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/50282
rollout_issue_url:
milestone: '13.8'
type: development
group: group::static analysis
default_enabled: false
