---
name: usage_data_instrumentation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/63520
rollout_issue_url:
milestone: '14.0'
type: development
group: group::product intelligence
default_enabled: false
