---
name: geo_lfs_object_replication_ssf
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/55251
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/247100
milestone: '13.10'
type: development
group: group::geo
default_enabled: false
