---
name: vulnerability_finding_fingerprints
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54608
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/322044
milestone: '13.10'
type: development
group: group::vulnerability research
default_enabled: false
