---
description: Counts of MAU updating epic notes
product_section: dev
product_stage: plan
product_group: group:product planning
product_category: epics_usage
value_type: number
status: implemented
milestone: "13.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/
time_frame: 7d
data_source: redis_hll
distribution:
- ee
tier:
- premium
- ultimate
