---
key_path: usage_activity_by_stage.manage.users_created
description: Number of users in an instance (need Dev to validate)
product_section: dev
product_stage: manage
product_group: group::access
product_category:
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
