---
key_path: usage_activity_by_stage.secure.user_sast_jobs
description: Count of SAST jobs per user per month
product_section: sec
product_stage: secure
product_group: group::static analysis
product_category: static_application_security_testing
value_type: number
status: data_available
time_frame: all
data_source: database
data_category: optional
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
