---
key_path: usage_activity_by_stage.manage.groups
description: Number of groups in an instance (Need Dev to confirm)
product_section: dev
product_stage: manage
product_group: group::access
product_category: subgroups
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
