---
key_path: usage_activity_by_stage.manage.user_auth_by_provider.two-factor
description: Number of users logging in using two factor authentication `https://gitlab.com/-/profile/two_factor_auth`
product_section: dev
product_stage: manage
product_group: group::access
product_category: authentication_and_authorization
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ce
tier:
- free
