---
key_path: counts.package_events_i_package_debian_push_package
description: A count of Debian packages that have been published
product_section: ops
product_stage: package
product_group: group::package
product_category: package registry
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ee
- ce
tier:
- free
- premium
- ultimate
skip_validation: false
