---
key_path: redis_hll_counters.user_packages.i_package_container_user_weekly
description: A weekly count of users that have published a container image to the registry
product_section: ops
product_stage: package
product_group: group::package
product_category: container registry
value_type: number
status: data_not_available
time_frame: all
data_source:
distribution:
- ee
- ce
tier:
- free
- premium
- ultimate
skip_validation: false
