---
key_path: usage_activity_by_stage_monthly.configure.project_clusters_disabled
description: Total GitLab Managed disabled clusters attached to projects
product_section: ops
product_stage: configure
product_group: group::configure
product_category: kubernetes_management
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
name: "count_distinct_user_id_from_<adjective describing: '(clusters.enabled = FALSE AND clusters.cluster_type = 3 AND clusters.created_at BETWEEN '2021-03-01 13:10:37.035725' AND '2021-03-29 13:10:37.035784')'>_clusters"
