---
key_path: usage_activity_by_stage_monthly.manage.user_auth_by_provider.google_oauth2
description: Number of unique user logins using Google OAuth authentication `https://docs.gitlab.com/ee/integration/google.html#google-oauth2-omniauth-provider`
product_section: dev
product_stage: manage
product_group: group::access
product_category: authentication_and_authorization
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
tier:
- free

