---
key_path: usage_activity_by_stage_monthly.manage.groups
description: Number of groups created per month `https://docs.gitlab.com/ee/user/group/#groups`
product_section: dev
product_stage: manage
product_group: group::access
product_category: subgroups
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
tier:
- free

