---
key_path: usage_activity_by_stage_monthly.manage.ldap_keys
description:
product_section: dev
product_stage: manage
product_group: group::access
product_category: auth
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
tier:
- free

