---
key_path: usage_activity_by_stage_monthly.manage.ldap_users
description: Number of users synced from LDAP `https://docs.gitlab.com/ee/administration/auth/ldap/#user-sync`
product_section: dev
product_stage: manage
product_group: group::access
product_category:
value_type: number
status: data_available
time_frame: 28d
data_source: database
distribution:
- ce
tier:
- free

