---
key_path: redis_hll_counters.user_packages.i_package_container_user_monthly
description: A monthly count of users that have published a container image to the registry
product_section: ops
product_stage: package
product_group: group::package
product_category: container registry
value_type: number
status: data_not_available
time_frame: 28d
data_source: redis_hll
distribution:
- ee
- ce
tier:
- free
- premium
- ultimate
skip_validation: false
