---
key_path: counts_monthly.packages
description: A monthly count of packages published to the registry
product_section: ops
product_stage: package
product_group: group::package
product_category: package registry
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ee
- ce
tier:
- free
- premium
- ultimate
skip_validation: false
