---
key_path: usage_activity_by_stage.secure.user_dependency_scanning_jobs
description: Total count of Dependency Scanning jobs run distinct per user
product_section: sec
product_stage: secure
product_group: group::composition analysis
product_category: dependency_scanning
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ee
tier:
- ultimate
